# =======================================================================================
#  GUARDIAN PROFILE: PARANOID | CHIMERA GUARDIAN ARCH
#  Defines the settings for the highest security level. This file is read by guardian-cli.
# =======================================================================================

# Human-readable name and description for the profile.
name: "Paranoid"
description: "Maximum security and anonymity. All system traffic is forcibly routed through the Tor network with a fail-closed kill switch. MAC address is randomized."

# Services to be managed when this profile is activated.
services:
  enable:
    - tor
  disable:
    - privoxy
    - dnscrypt-proxy

# Network interface card (NIC) specific settings.
network:
  # Enables MAC address randomization for the primary network interface.
  mac_spoofing: true

# Firewall configuration.
firewall:
  # The engine responsible for applying the rules. For transparent proxying and a
  # robust kill switch, direct control via 'iptables' is required.
  engine: "iptables"

  # If true, the firewall will block all non-Tor traffic.
  kill_switch: true

  # Specific iptables commands for creating the transparent proxy and kill switch.
  # These rules are executed in order by the guardian-cli script.
  rules:
    # --- NAT Table (for redirecting traffic) ---
    # 1. Redirect all DNS requests (UDP/TCP port 53) to Tor's DNS port (DNSPort).
    - "iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to-ports 5353"
    - "iptables -t nat -A OUTPUT -p tcp --dport 53 -j REDIRECT --to-ports 5353"
    
    # 2. Redirect all other outgoing TCP traffic to Tor's transparent proxy port (TransPort).
    - "iptables -t nat -A OUTPUT -p tcp --syn -j REDIRECT --to-ports 9040"

    # --- FILTER Table (for the kill switch) ---
    # 3. Allow all traffic generated by the 'debian-tor' user itself. This is critical.
    - "iptables -A OUTPUT -m owner --uid-owner debian-tor -j ACCEPT"
    
    # 4. Allow all loopback traffic (for local services to communicate).
    - "iptables -A OUTPUT -o lo -j ACCEPT"
    
    # 5. Set the default policy for all other outbound traffic to REJECT.
    #    This is the kill switch. If a packet doesn't match the rules above, it's blocked.
    - "iptables -P OUTPUT REJECT"